= Quick notes on Common Lisp
:Author: Nguyễn Hà Dương (cmpitg)
:Email: <cmpitg@gmail.com>
:toc: left
:toclevels: 4
:numbered:
:icons: font
:pygments-css: class
:imagesdirs: ../assets/images

TODO: Code examples

* http://rosettacode.org

* http://www.cliki.net/current%20recommended%20libraries

* Notes about peek-char

* Notes about discard-next-char

* Notes about +(read input-stream t nil t)+ idiom:
** +(with-input-from-string (is " ") (read is nil 'the-end))+ returns +THE-END+
** +(with-input-from-string (is " ") (read is t <anything>))+ throws error.
** +recursive-p+ is +t+ means we expect this +read+ call is inside a reader macro

* Notes about +read-delimited-list+ and reader macro: http://www.lispworks.com/documentation/HyperSpec/Body/f_rd_del.htm

* Notes about writing reader macro in JSON: https://gist.github.com/chaitanyagupta/9324402

* Notes about writing reader macros in practice with https://common-lisp.net/project/named-readtables/

'''

== Recommended setup (objective)

* Emacs with Slime
* Quicklisp as package manager

== Tips and tricks

=== Getting current working directory

* Avoid +\*default-pathname-defaults*+, it's implementation-dependent.
* (SBCL) SBCL: +(sb-posix:getcwd)+.

[source,lisp,linenums]
----
;; Require cl-cwd
(cl-cwd:get-cwd)

;; Require osicat
(osicat:current-directory)
----

=== Changing current working directory/+cd+

[source,lisp,linenums]
----
;; Only in SBCL
(sb-posix:cwd "/tmp")

;; Require cl-cwd
(cl-cwd:cwd "/tmp")

;; Require cl-cwd, when you'd like to change it temporarily
(cl-cwd:with-cwd "/tmp/"
  (format t "~A" (directory (make-pathname :directory '(:relative ".")
                                           :name :wild
                                           :type :wild))))
----


=== Getting current file

+\*load-truename*+ or +\*load-pathname*+, returning truename and pathname,
respectively.  In modern system and practice, two kinds of pathnames could be
used interchangably.

=== Reading/slurping file

Avoid using +open+ and +close+ as 1) it's error-prone, and 2) the file might
not properly closed if you don't properly handle it.  Instead, use
+with-open-file+.

* Simplest way to read a line from a file:
+
[source,lisp,linenums]
----
(with-open-file (in #P"/tmp/tmp.txt")
  (format t "~A~%" (read-line in)))
----

* Useful functions: +read-line+, +read-char+, +peek-char+, +file-position+
  (jumping to a position).

* To read whole file:

** The best way is probably to use +read-utf-8-string+ from +trivial-utf-8+
   library:
+
[source,lisp,linenums]
----
(defun slurp (filespec)
  "Reads and returns the whole file as string."
  (with-open-file (in filespec :element-type '(unsigned-byte 8))
    (trivial-utf-8:read-utf-8-string in :stop-at-eof t)))
----

** Or if you don't care about encoding thing and just want to read ASCII, one
   way is to use +read-sequence+ with +file-length+ to read the content of the
   file into a string:
+
[source,lisp,linenums]
----
(with-open-file (in #P"/tmp/tmp.txt")
  (let ((seq (make-string (file-length in))))
    (read-sequence seq in)
    seq))
----

=== Merging paths

[source,lisp,linenums]
----
(merge-pathnames #p"lib/misc" #p"/home/batman")  ;; ⇨ #P"/home/lib/misc"
(merge-pathnames #p"lib/misc" #p"/home/batman/") ;; ⇨ #P"/home/batman/lib/misc"
(merge-pathnames #p"lib/misc" #p"home/batman")   ;; ⇨ #P"home/lib/misc"
(merge-pathnames #p"lib/misc" #p"home/batman/")  ;; ⇨ #P"home/batman/lib/misc"
----
=== Getting path to a system loaded with ASDF

[source,lisp,linenums]
----
(asdf:system-source-directory :optima) ;; ⇨ #P"/home/batman/quicklisp/dists/quicklisp/software/optima-20150302-git/"
----
----
